import { ReactComponent as IconCampaign } from '../assets/icon_service_campaign.svg';
import { ReactComponent as IconDonation } from '../assets/icon_service_donation.svg';
import { ReactComponent as IconVolunteering } from '../assets/icon_service_volunteering.svg';

const oportunidades = [
    {
        id: '1',
        category: "vaga de voluntariado",
        title: "Arrecadação de alimentos para moradores de rua",
        status: "SP Invisível",
        value_service: "2-6",
        info_service: "itens disponíveis",
        icon: <IconVolunteering />,
        button: "participar",
        location: "Natal, RN",
    },
    {
        id: '2',
        category: "doação de materiais",
        title: "Arrecadação de alimentos para moradores de rua",
        status: "Invisível",
        value_service: "36",
        info_service: "itens disponíveis",
        icon: <IconDonation />,
        button: "doar",
        location: "Natal, RN",
    },
    {
        id: '3',
        category: "campanha de arrecadação",
        title: "Arrecadação de alimentos para moradores de rua",
        status: "SP Invisível",
        value_service: "R$5.000",
        info_service: "valor esperado",
        icon: <IconDonation />,
        button: "doar",
        location: "Natal, RN",
    },
    {
        id: '4',
        category: "doação de materiais",
        title: "Arrecadação de alimentos para moradores de rua",
        status: "SP Invisível",
        value_service: "2-6",
        info_service: "horaas semana",
        icon: <IconDonation />,
        button: "doar",
        location: "Natal, RN",
    },
    {
        id: '5',
        category: "vaga de voluntariado",
        title: "Entrega de roupas e alimentos para moradores de rua",
        status: "SP Invisível",
        value_service: "2-6",
        info_service: "horaas semana",
        icon: <IconVolunteering />,
        button: "participar",
        location: "Natal, RN",
    },
    {
        id: '6',
        category: "campanha de arrecadação",
        title: "Arrecadação de alimentos para moradores de rua",
        status: "SP Invisível",
        value_service: "R$5.000",
        info_service: "valor esperado",
        icon: <IconCampaign />,
        button: "contribuir",
        location: "Natal, RN",
    },
    {
        id: '7',
        category: "doação de materiais",
        title: "Arrecadação de alimentos para moradores de rua",
        horas_semanais: "Invisível",
        status: "SP Invisível",
        value_service: "36",
        info_service: "itens disponíveis",
        icon: <IconDonation />,
        button: "doar",
        location: "Natal, RN",
    },
    {
        id: '8',
        category: "vaga de voluntariado",
        title: "Entrega de roupas e alimentos para moradores de rua",
        horas_semanais: "Invisível",
        status: "SP Invisível",
        value_service: "2-6",
        info_service: "horas semanais",
        icon: <IconVolunteering />,
        button: "participar",
        location: "Natal, RN",
    },
    {
        id: '9',
        category: "doação de materiais",
        title: "Arrecadação de alimentos para moradores de rua",
        horas_semanais: "Invisível",
        status: "SP Invisível",
        value_service: "36",
        info_service: "itens disponíveis",
        icon: <IconDonation />,
        button: "doar",
        location: "Natal, RN",
    },
];

export default oportunidades;